### ISSUE TITLE
Any plans to support other GLM families & link functions?

### ISSUE THREAD

**Issue by tomwenseleers** [dongjli/bravo#2]
Thanks for the great package. Was just wondering if there might be any plans to extend this package to also support other error distributions (& link functions) than Gaussian - e.g. the standard GLM exponential family distributions & link functions? If not, would you happen to know what is currently the fastest Bayesian variable selection method available in R or Python for that setting?

**Comment by somakd** [comment]
We are currently developing methods for GLMs, and the corresponding software will be made available.
